A

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -160,20 +160,20 @@ stage('Validate RG - Resources') {
         set FILE=azure-adf-e2e\\arm-templates\\resource-group\\rg.json
         set PSFILE=validate-rg-resources.ps1
 
-        echo $ErrorActionPreference = 'Stop' > %PSFILE%
-        echo $json = Get-Content '%FILE%' ^| ConvertFrom-Json >> %PSFILE%
-        echo # ---- Resource Group Name validation ---- >> %PSFILE%
-        echo $rgParam = $json.parameters.PSObject.Properties ^| Where-Object { $_.Name -match 'resource.*group.*name' } >> %PSFILE%
-        echo if (-not $rgParam) { >> %PSFILE%
-        echo   $ln = ((Get-Content '%FILE%') ^| Select-String -Pattern 'parameters' ^| Select -First 1).LineNumber >> %PSFILE%
-        echo   Write-Host \"ERROR: Line $ln, File %FILE%, Where ResourceGroupName, What Parameter missing\" >> %PSFILE%
-        echo   exit 1 >> %PSFILE%
+        echo foreach ($k in $expected.Keys) { >> %PSFILE%
+        echo   $param = $json.parameters.PSObject.Properties[$k].Value >> %PSFILE%
+        echo   if (-not $param) { >> %PSFILE%
+        echo     $ln = ((Get-Content '%FILE%') ^| Select-String -SimpleMatch $k ^| Select -First 1).LineNumber >> %PSFILE%
+        echo     Write-Host \"ERROR: Line $ln, File %FILE%, Where parameter:$k, What missing\" >> %PSFILE%
+        echo     exit 1 >> %PSFILE%
+        echo   } >> %PSFILE%
+        echo   if ($param.defaultValue -ne $expected[$k]) { >> %PSFILE%
+        echo     $ln = ((Get-Content '%FILE%') ^| Select-String -SimpleMatch $k ^| Select -First 1).LineNumber >> %PSFILE%
+        echo     Write-Host \"ERROR: Line $ln, File %FILE%, Where parameter:$k, What wrong default value\" >> %PSFILE%
+        echo     exit 1 >> %PSFILE%
+        echo   } >> %PSFILE%
         echo } >> %PSFILE%
-        echo if ([string]::IsNullOrWhiteSpace($rgParam.Value.defaultValue)) { >> %PSFILE%
-        echo   $ln = ((Get-Content '%FILE%') ^| Select-String -SimpleMatch $rgParam.Name ^| Select -First 1).LineNumber >> %PSFILE%
-        echo   Write-Host \"ERROR: Line $ln, File %FILE%, Where $($rgParam.Name), What Default value empty\" >> %PSFILE%
-        echo   exit 1 >> %PSFILE%
-        echo } >> %PSFILE%
+
 
 
         REM ---- Required resource types ----
