A

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -161,20 +161,33 @@ stage('Validate RG - Resources') {
         set PSFILE=validate-rg-resources.ps1
 
         echo foreach ($k in $expected.Keys) { >> %PSFILE%
-        echo   $param = $json.parameters[$k] >> %PSFILE%
+        echo   $param = $json.parameters.$k >> %PSFILE%
+
         echo   if (-not $param) { >> %PSFILE%
         echo     $ln = ((Get-Content '%FILE%') ^| Select-String -SimpleMatch $k ^| Select -First 1).LineNumber >> %PSFILE%
-        echo     Write-Host \"ERROR: Line $ln, File %FILE%, Where parameter:$k, What missing\" >> %PSFILE%
+        echo     Write-Host \"ERROR: Line $ln, File %FILE%, Where parameter:$k, What parameter block missing\" >> %PSFILE%
         echo     exit 1 >> %PSFILE%
         echo   } >> %PSFILE%
+
+        echo   if (-not $param.defaultValue) { >> %PSFILE%
+        echo     $ln = ((Get-Content '%FILE%') ^| Select-String -SimpleMatch $k ^| Select -First 1).LineNumber >> %PSFILE%
+        echo     Write-Host \"ERROR: Line $ln, File %FILE%, Where parameter:$k, What defaultValue missing\" >> %PSFILE%
+        echo     exit 1 >> %PSFILE%
+        echo   } >> %PSFILE%
+
+        echo   if (-not $param.type) { >> %PSFILE%
+        echo     $ln = ((Get-Content '%FILE%') ^| Select-String -SimpleMatch $k ^| Select -First 1).LineNumber >> %PSFILE%
+        echo     Write-Host \"ERROR: Line $ln, File %FILE%, Where parameter:$k, What type missing\" >> %PSFILE%
+        echo     exit 1 >> %PSFILE%
+        echo   } >> %PSFILE%
+
         echo   if ($param.defaultValue -ne $expected[$k]) { >> %PSFILE%
         echo     $ln = ((Get-Content '%FILE%') ^| Select-String -SimpleMatch $k ^| Select -First 1).LineNumber >> %PSFILE%
-        echo     Write-Host \"ERROR: Line $ln, File %FILE%, Where parameter:$k, What wrong default value\" >> %PSFILE%
+        echo     Write-Host \"ERROR: Line $ln, File %FILE%, Where parameter:$k, What defaultValue mismatch\" >> %PSFILE%
         echo     exit 1 >> %PSFILE%
         echo   } >> %PSFILE%
+
         echo } >> %PSFILE%
-
-
 
 
         REM ---- Required resource types ----
